name: Check Pact broker image

on:
  pull_request:
    paths:
      - 'ci/docker/pact-broker/**'

permissions:
  contents: read

jobs:
  check-docker-base-images-are-manifests:
    uses: govuk-pay/pay-ci/.github/workflows/_validate_docker_image_is_manifest.yml@c1bed255fa76164f86f2b0f0f20df26ea58ab1c6
    with:
      dockerfile: ./ci/docker/pact-broker/Dockerfile
